[package]
name = "topos-formats"
version = "0.2.0"
edition = "2024"
license.workspace = true
repository.workspace = true
description = "Find Bible references in HTML, subtitles, EPUB, and PDF, with format-specific locations"

[dependencies]
topos-lib = { path = "../topos-lib" }
itertools = { workspace = true }
thiserror = { workspace = true }

htmloc = { workspace = true, optional = true }
epub = { version = "2.1.5", optional = true }
roxmltree = { version = "0.21.1", optional = true }
mupdf = { version = "0.8.0", optional = true }
serde_json = { workspace = true, optional = true }

[features]
default = ["html", "srt", "epub", "json", "xml"]
html = ["dep:htmloc"]
srt = []
epub = ["dep:epub", "dep:roxmltree"]
json = ["dep:serde_json"]
xml = ["dep:roxmltree"]
# Needs MuPDF to build
pdf = ["dep:mupdf"]
